### ISSUE TITLE
Support for simpleledger: and slptest: prefixes

### ISSUE THREAD

**Issue by Polve** [ealmansi/cashaddrjs#14]
To use SLP (Simple Ledger Protocol) we need to use two new prefixes: "simpleledger" for production and "slptest" for addresses.

Is it possible to add them to the VALID_PREFIXES?

Otherwise, it could be useful to let the user specify which prefixes are valid.

**Comment by blockparty-sh** [comment]
There is this repo:

https://github.com/simpleledger/cashaddrjs

Maybe these could be merged into this repo if @ealmansi is interested? If so I can do a PR

**Comment by ealmansi** [comment]
this library is in maintenance mode, only bug fixes and security upgrades will be added going forward

**Comment by Polve** [comment]
is there some alternative library to consider for the future?
